version: "3.8"

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8002:8000
    container_name: app
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@172.16.238.11/hello_fastapi_dev
    depends_on:
      - db
    networks:
      app-network:
        ipv4_address: 172.16.238.10
  db:
    image: postgres:13.1-alpine
    container_name: app-postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev
    ports:
      - 5432:5432
    networks:
      app-network:
        ipv4_address: 172.16.238.11
  prometheus:
    image: prom/prometheus:latest
    container_name: app-prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./promethous/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      app-network:
        ipv4_address: 172.16.238.12
  grafana:
    image: grafana/grafana:latest
    container_name: app-grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring
    depends_on:
      - prometheus
    networks:
      app-network:
        ipv4_address: 172.16.238.13
  node-exporter:
    image: prom/node-exporter
    container_name: app-node-exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    environment:
      - "TZ=Asia/Seoul"
    command:
      - --collector.disable-defaults
      - '--collector.cpu'
      - '--collector.loadavg'
    depends_on:
      - prometheus
volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./promethous
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana
  postgres_data:

networks:
  app-network:
    name: app-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24