global:
  scrape_interval: "1m"
  scrape_timeout: "10s"
  evaluation_interval: "1m"
alerting:
  alertmanagers:
    - timeout: "10s"
      api_version: v2
      path_prefix: /
      scheme: http
      follow_redirects: true
      enable_http2: true
      static_configs:
        - targets: []
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'app'
    scrape_interval: 5s
    metrics_path: /metrics/app
    static_configs:
      - targets: ['app:8000']
  - job_name: 'server'
    scrape_interval: 5s
    metrics_path: /metrics/server
    static_configs:
      - targets: ['app-node-exporter:9100']