[project]
name = "delalake-for-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "daft>=0.1.3",
    "dask>=2025.2.0",
    "datafusion>=44.0.0",
    "deltalake>=0.25.1",
    "duckdb>=1.2.0",
    "pandas>=2.2.3",
    "polars>=1.23.0",
    "pyarrow>=18.1.0",
]
