[project]
name = "20250722"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.13"
dependencies = [
    "boto3>=1.39.10",
    "duckdb>=1.3.2",
    "pandas>=2.3.1",
    "pyarrow>=21.0.0",
]
