version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'

  nifi-registry:
    image: 'apache/nifi-registry:latest'
    container_name: nifi-registry
    ports:
      - '18080:18080'
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080

  nifi1:
    image: 'apache/nifi:latest'
    container_name: nifi1
    ports:
      - '8081:8080'
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=nifi-key
      - NIFI_REGISTRY_URL=http://nifi-registry:18080

  nifi2:
    image: 'apache/nifi:latest'
    container_name: nifi2
    ports:
      - '8082:8080'
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=nifi-key
      - NIFI_REGISTRY_URL=http://nifi-registry:18080

  nifi3:
    image: 'apache/nifi:latest'
    container_name: nifi3
    ports:
      - '8083:8080'
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=nifi-key
      - NIFI_REGISTRY_URL=http://nifi-registry:18080

networks:
  default:
    name: nifi-network